# Generated by Django 3.2.4 on 2021-06-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gordas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb', models.CharField(default='', max_length=50, null=True)),
                ('descr', models.TextField(default='', max_length=500, null=True)),
                ('date', models.CharField(default='', max_length=20, null=True)),
                ('calif', models.CharField(default='', max_length=20, null=True)),
                ('img', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='lonches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb', models.CharField(default='', max_length=50, null=True)),
                ('descr', models.TextField(default='', max_length=500, null=True)),
                ('date', models.CharField(default='', max_length=20, null=True)),
                ('calif', models.CharField(default='', max_length=20, null=True)),
                ('img', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='tacos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb', models.CharField(default='', max_length=50, null=True)),
                ('descr', models.TextField(default='', max_length=500, null=True)),
                ('date', models.CharField(default='', max_length=20, null=True)),
                ('calif', models.CharField(default='', max_length=20, null=True)),
                ('img', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
    ]
